name: remind

on:
  schedule:
    - cron: "0 9 * * *" # 18:00 JST

permissions:
  contents: read
  issues: write

jobs:
  remind:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TZ: Asia/Tokyo
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-node

      - name: Remind three days before
        run: pnpm zunocal remind 3 --config config.ci.jsonc
        env:
          TOKEN: ${{ github.token }}

      - name: Remind one day before
        run: pnpm zunocal remind 1 --config config.ci.jsonc
        env:
          TOKEN: ${{ github.token }}
